version: '3'
services:
    nodern:
        container_name: gameish
        image: node:latest
        user: node
        build:
            context: .
            dockerfile: dockerfile
#            args:
#                - CHOSE_PROXY=artifactory
        tty: true
        working_dir: /home/node/app
        ports:
            - 8090:8090
            - 19000-19002:19000-19002
        volumes:
            - ./global:/home/node/.npm-global
            - ./local:/home/node/app
        environment:
#            - CHOKIDAR_USEPOLLING=true
            - NPM_CONFIG_PREFIX=/home/node/.npm-global
            - NPM_CONFIG_LOGLEVEL=info
            - ADB_IP=192.168.1.8
            - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.6
            - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0